# Generated by Django 4.0 on 2024-03-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance_courses_user_user_type_subjects_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=3, max_length=10),
        ),
    ]
