# Generated by Django 4.0 on 2024-05-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_course_subject_discipline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinstance',
            old_name='public',
            new_name='ispublic',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='public',
            new_name='ispublic',
        ),
    ]
