# Generated by Django 4.0 on 2024-05-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_public_classinstance_ispublic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinstance',
            name='ispublic',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ispublic',
        ),
        migrations.AddField(
            model_name='classinstance',
            name='mode',
            field=models.CharField(choices=[('publico', 'publico'), ('privado', 'privado'), ('moderado', 'moderado')], default='moderado', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='mode',
            field=models.CharField(choices=[('publico', 'publico'), ('privado', 'privado'), ('moderado', 'moderado')], default='moderado', max_length=50),
        ),
    ]
