# Generated by Django 4.0 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_classinstance_ispublic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='accounts.Student'),
        ),
    ]
