# Generated by Django 4.0 on 2024-05-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tempfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(choices=[('rut', 'rut'), ('pasaporte', 'pasaporte')], max_length=50, null=True),
        ),
    ]
