# Generated by Django 4.0 on 2024-03-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subjects_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Staff'), (2, 'Student')], default=2, max_length=10),
        ),
    ]
