# Generated by Django 4.0 on 2024-05-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_student_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(choices=[('rut', 'rut'), ('pasaporte', 'pasaporte')], default='00.000.000-0', max_length=50),
            preserve_default=False,
        ),
    ]
