# Generated by Django 4.0 on 2024-05-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(choices=[('rut', 'rut'), ('pasaporte', 'pasaporte')], max_length=50, unique=True),
        ),
    ]
