# Generated by Django 4.0 on 2024-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_type',
            field=models.CharField(choices=[('rut', 'rut'), ('pasaporte', 'pasaporte')], max_length=50, null=True),
        ),
    ]
