# Generated by Django 4.0 on 2024-03-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Teacher'), (2, 'Studentqq')], default=2, max_length=10),
        ),
    ]
