# Generated by Django 4.0 on 2024-03-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], max_length=10),
        ),
    ]
