# Generated by Django 4.0 on 2024-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentclassrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document_number',
            field=models.CharField(default='20.237.612-6', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(choices=[('rut', 'rut'), ('pasaporte', 'pasaporte')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='document_number',
            field=models.CharField(default='20.237.612-6', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='document_type',
            field=models.CharField(choices=[('rut', 'rut'), ('pasaporte', 'pasaporte')], max_length=50, null=True),
        ),
    ]
