# Generated by Django 4.0 on 2024-03-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='dateandhour',
            field=models.DateTimeField(null=True),
        ),
    ]
