# Generated by Django 4.0 on 2024-03-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_attendance_dateandhour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='estado',
        ),
    ]
