# Generated by Django 4.0 on 2024-04-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_attendance_dateandhour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='subject_id',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('lunes', 'lunes'), ('martes', 'martes'), ('miercoles', 'miercoles'), ('jueves', 'jueves'), ('viernes', 'viernes'), ('sabado', 'sabado'), ('domingo', 'domingo')], default=None, max_length=15)),
                ('time', models.TimeField()),
                ('alumnos_horario', models.ManyToManyField(to='accounts.Students')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='horario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.horario'),
            preserve_default=False,
        ),
    ]
