# Generated by Django 4.0 on 2024-04-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_clase_subject_id_horario_clase_horario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='alumnos_horario',
            field=models.ManyToManyField(blank=True, to='accounts.Students'),
        ),
    ]
