# Generated by Django 4.0 on 2024-04-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_horario_alumnos_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('alumno', 'alumno'), ('profesor', 'profesor'), ('apoderado', 'apoderado')], max_length=10),
        ),
    ]
