# Generated by Django 4.0 on 2024-04-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects'),
        ),
    ]
