# Generated by Django 4.0 on 2024-04-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_horario_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='horario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.horario'),
        ),
    ]
