# Generated by Django 4.0 on 2024-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_clase_horario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='date_and_hour',
        ),
        migrations.AddField(
            model_name='clase',
            name='date',
            field=models.DateField(default='2024-04-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
