# Generated by Django 4.0 on 2024-04-20 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_clase_date_and_hour_clase_date_clase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
