# Generated by Django 4.0 on 2024-04-24 22:43

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_clase_created_at_clase_updated_at_horario_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='clase',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.teachers'),
        ),
        migrations.AddField(
            model_name='clase',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='document_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='document_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='profesores',
            field=models.ManyToManyField(to='accounts.Teachers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='SolicitudProfesorSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAlumnoSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAlumnoHorario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('horario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.horario')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
    ]
