# Generated by Django 4.0 on 2024-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_subjects_staff_id_clase_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudalumnohorario',
            name='tipo',
            field=models.CharField(choices=[('add-alumno', 'add-alumno'), ('remove-alumno', 'remove-alumno')], default='add-alumno', max_length=255),
        ),
    ]
