# Generated by Django 4.0 on 2024-04-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_solicitudalumnohorario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='day_of_week',
            field=models.CharField(choices=[('lunes', 'lunes'), ('martes', 'martes'), ('miércoles', 'miércoles'), ('jueves', 'jueves'), ('viernes', 'viernes'), ('sábado', 'sábado'), ('domingo', 'domingo')], default=None, max_length=15),
        ),
    ]
