# Generated by Django 4.0 on 2024-04-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_clase_time_remove_clase_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='num_max_alumnos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horario',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='num_max_alumnos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
