# Generated by Django 4.0 on 2024-04-30 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_horario_num_max_alumnos_horario_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAlumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumnos', models.ManyToManyField(related_name='grupos', to='accounts.Students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAlumnoGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('add-alumno', 'add-alumno'), ('remove-alumno', 'remove-alumno')], default='add-alumno', max_length=255)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.grupoalumnos')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudalumnohorario',
            name='horario_id',
        ),
        migrations.RemoveField(
            model_name='solicitudalumnohorario',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='horario_id',
        ),
        migrations.AddField(
            model_name='clase',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='clases', to='accounts.Students'),
        ),
        migrations.AddField(
            model_name='clase',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='num_max_alumnos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clase',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.subjects'),
        ),
        migrations.AddField(
            model_name='clase',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='time_start',
            field=models.TimeField(default='12:12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudalumnosubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudalumnosubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitudprofesorsubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudprofesorsubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='SolicitudAlumnoHorario',
        ),
    ]
