# Generated by Django 4.0 on 2024-05-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_grupoalumnos_solicitudalumnogrupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField(null=True)),
                ('state', models.CharField(choices=[('proximamente', 'proximamente'), ('realizada', 'realizada'), ('realizada-parcial', 'realizada-parcial'), ('cancelada', 'cancelada')], default='proximamente', max_length=50)),
                ('num_max_students', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('firstname', models.CharField(max_length=45, null=True)),
                ('lastname', models.CharField(max_length=45, null=True)),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=50, null=True)),
                ('document_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(related_name='groups', to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_max_students', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.discipline')),
                ('students', models.ManyToManyField(to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='grupoalumnos',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='grupoalumnos',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='solicitudalumnogrupo',
            name='grupo_id',
        ),
        migrations.RemoveField(
            model_name='solicitudalumnogrupo',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='solicitudalumnosubject',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='solicitudalumnosubject',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='solicitudprofesorsubject',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='solicitudprofesorsubject',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='admin',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='estado',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clase_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user_estado_previo',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_previous_state',
            field=models.CharField(choices=[('asistire', 'Asistiré'), ('no-asistire', 'no-asistire'), ('no-responde', 'No responde')], default='no-responde', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('alumno', 'alumno'), ('profesor', 'profesor'), ('apoderado', 'apoderado'), ('admin', 'admin')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='GrupoAlumnos',
        ),
        migrations.DeleteModel(
            name='SolicitudAlumnoGrupo',
        ),
        migrations.DeleteModel(
            name='SolicitudAlumnoSubject',
        ),
        migrations.DeleteModel(
            name='SolicitudProfesorSubject',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='studentsubjectrequest',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='classinstance',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_students', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='classinstance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='classinstance',
            name='teachers',
            field=models.ManyToManyField(to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.classinstance'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.student'),
        ),
    ]
