# Generated by Django 4.0 on 2024-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_classinstance_discipline_student_studentgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer')], max_length=15, null=True),
        ),
    ]
