# Generated by Django 4.0 on 2024-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_user_email_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
